// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TryTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void try() {
    driver.Navigate().GoToUrl("http://182.77.61.134/arclite.uat/Account/Login?ReturnUrl=%2Farclite.uat%3Fsales");
    driver.Manage().Window.Size = new System.Drawing.Size(858, 659);
    driver.FindElement(By.Id("UserName")).Click();
    driver.FindElement(By.Id("UserName")).SendKeys("admin");
    driver.FindElement(By.Id("Password")).SendKeys("admin");
    driver.FindElement(By.Id("btnlogin")).Click();
    driver.FindElement(By.CssSelector(".arc-sales-icon-header")).Click();
    driver.SwitchTo().Frame(0);
    driver.FindElement(By.CssSelector(".fa-plus")).Click();
    driver.FindElement(By.CssSelector("#requested-end-date-dtp > .input-group-text")).Click();
    driver.FindElement(By.CssSelector(".datepicker-days .next > .fa")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(5) > .day:nth-child(7)")).Click();
  }
}
