// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ArclitesettingsTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void arclitesettings()
    {
        driver.Navigate().GoToUrl("http://182.77.61.134/arclite.uat/Account/");
        driver.Manage().Window.Size = new System.Drawing.Size(1501, 928);
        driver.FindElement(By.Id("UserName")).Click();
        driver.FindElement(By.Id("UserName")).SendKeys("admin");
        driver.FindElement(By.Id("Password")).SendKeys("admin");
        driver.FindElement(By.Id("btnlogin")).Click();
        driver.FindElement(By.Id("arc-config")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".fa-plus")).Click();
        driver.FindElement(By.CssSelector("#btnSave > .fa")).Click();
        driver.FindElement(By.CssSelector("#btnclose > .fas")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.Id("personnel")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".fa-plus")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".fa-plus"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
        //    var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
      //      builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector(".float-right > .fa")).Click();
        driver.FindElement(By.CssSelector(".modal-footer:nth-child(5) > #btnSave")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".modal-footer:nth-child(5) > #btnSave"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
          //  var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
          //  builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector(".modal-footer:nth-child(5) .fas")).Click();
        driver.FindElement(By.Id("btnSave")).Click();
        driver.FindElement(By.CssSelector(".modal-footer:nth-child(2) .fas")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.Id("assets")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".fa-plus")).Click();
        driver.FindElement(By.CssSelector(".row:nth-child(1) .form-group .btn")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".row:nth-child(1) .form-group .btn"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
         //   var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
         //   builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector("#addUpdateAssetType #btnSave")).Click();
        {
            var element = driver.FindElement(By.CssSelector("#addUpdateAssetType #btnSave"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
         //   var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
        //    builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector("#addUpdateAssetType .fas")).Click();
        driver.FindElement(By.CssSelector(".row:nth-child(4) .col-md-1 .fa")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".row:nth-child(4) .btn"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
       //     var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
       //     builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector(".modal-footer:nth-child(5) > #btnSave")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".modal-footer:nth-child(5) > #btnSave"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
        //    var element = driver.FindElement(By.tagName("body"));
           Actions builder = new Actions(driver);
       //     builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector(".modal-footer:nth-child(5) .fas")).Click();
        driver.FindElement(By.Id("btnSave")).Click();
        {
            var element = driver.FindElement(By.Id("btnSave"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
       //     var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
          //  builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector("#addEditAsset .fas")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.Id("customer")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".fa-plus")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".fa-plus"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
        //    var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
         //   builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.Id("btnSave")).Click();
        driver.FindElement(By.CssSelector("#btnclose > .fas")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.Id("supplier")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".col-md-6 > .btn")).Click();
        driver.FindElement(By.CssSelector(".fa-save")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".fa-save"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
        //    var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
          //  builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector("#btnclose > .fas")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.Id("checklist")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector(".fa-plus")).Click();
        driver.FindElement(By.CssSelector(".fa-plus")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".fa-plus"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
//var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
         //   builder.MoveToElement(element, 0, 0).Perform();
        }
        {
            var element = driver.FindElement(By.Id("btnSaveCategory"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
           // var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
          //  builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector("#btnSaveCategory > .fas")).Click();
        {
            var element = driver.FindElement(By.CssSelector("#btnSaveCategory > .fas"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
         //   var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
        //    builder.MoveToElement(element, 0, 0).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".col-md-12 > .arc-btn-icon-red"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
         //   var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
         //   builder.MoveToElement(element, 0, 0).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".col-md-12 > .arc-btn-icon-red > .fas"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        driver.FindElement(By.CssSelector(".col-md-12 > .arc-btn-icon-red > .fas")).Click();
        {
        //    var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
        //    builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector("#btnSaveChecklist > .fa")).Click();
        driver.FindElement(By.CssSelector(".fa-arrow-left")).Click();
        driver.SwitchTo().DefaultContent();
        driver.FindElement(By.Id("settings")).Click();
    }
}
